# Generated by Django 4.1 on 2023-03-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrequests',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
