# Generated by Django 4.1 on 2023-03-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinfo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user_for',
        ),
    ]
