# Generated by Django 4.1 on 2023-03-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userinfo_user_alter_userinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_for',
        ),
    ]
