# Generated by Django 4.1 on 2023-03-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userinfo_address_alter_userinfo_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='degree_title',
            field=models.CharField(default='bscs', max_length=20),
        ),
    ]
