# Generated by Django 4.1 on 2023-03-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userinfo_degree_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_for', models.CharField(default='bscs', max_length=10)),
                ('course_time', models.CharField(default='morning', max_length=20)),
            ],
        ),
    ]
