# Generated by Django 4.1 on 2023-03-20 07:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('enrollment_fees', models.IntegerField()),
                ('course_fees', models.IntegerField()),
                ('monthly_fees', models.IntegerField(default=2000)),
                ('balance', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('penalty', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
