# Generated by Django 4.1 on 2023-03-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_votes_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='course_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fees',
            name='enrollment_fees',
            field=models.IntegerField(default=5000),
        ),
    ]
