# Generated by Django 4.1 on 2023-03-31 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentreal',
            name='AvailableCourses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.availablecourses'),
        ),
        migrations.AlterField(
            model_name='enrollmentreal',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
