# Generated by Django 4.1 on 2023-03-31 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_enrollmentreal_availablecourses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentReal',
        ),
    ]
