# Generated by Django 4.1 on 2023-03-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentreal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='EnrollmentReal',
        ),
    ]
