# Generated by Django 4.1 on 2023-04-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_student_delete_uservotes_delete_voting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_current_student',
            field=models.BooleanField(default=True),
        ),
    ]
