# Generated by Django 4.1 on 2023-04-06 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_student_is_current_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_current_student',
        ),
    ]
