# Generated by Django 4.1 on 2023-04-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_uservotes_voting_alter_otherrequests_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
