# Generated by Django 4.1 on 2023-04-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_userinfo_is_student_userinfo_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherrequests',
            name='has_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='degree_title',
            field=models.CharField(blank=True, default='bscs', max_length=20),
        ),
    ]
