# Generated by Django 4.1 on 2023-04-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='product_price',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('study', 'Study'), ('notes', 'Notes'), ('book', 'Book')], default='study', max_length=50),
        ),
    ]
