# Generated by Django 4.1 on 2023-05-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_product_category_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='products',
            new_name='product',
        ),
    ]
