# Generated by Django 4.1 on 2023-05-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_products_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
