# Generated by Django 4.1 on 2023-04-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_postlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
    ]
