# Generated by Django 4.1 on 2023-05-06 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalorder',
            name='customer_name',
            field=models.CharField(default='Customer', max_length=50),
        ),
        migrations.AddField(
            model_name='totalorder',
            name='waiter_name',
            field=models.CharField(default='Hello Kitty', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemorders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='totalorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='totalorder',
            name='extra_charges',
            field=models.IntegerField(default=0),
        ),
    ]
