# Generated by Django 4.1 on 2023-05-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_itemorders_order_number_alter_item_item_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemOrders',
            new_name='Cart',
        ),
    ]
